export const settings = {
  "hk": {
    "titleindex": "Latest Mobile Price In Hong Kong | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Hong Kong, Mobile Price hk, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,hk,Hong Kong,pictures,photos",
    "country": "Hong Kong",
    "symbol": "HK$",
    "currency": "USD",
    "exchangerates": "7.850515463917526",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Hong Kong & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "sg": {
    "titleindex": "Latest Mobile Price In Singapore | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Singapore, Mobile Price sg, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,sg,Singapore,pictures,photos",
    "country": "Singapore",
    "symbol": "SGD",
    "currency": "SGD",
    "exchangerates": "1.42",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Singapore & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "co": {
    "titleindex": "Mobile Price In Colombia | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Colombia, Smartphone Price co, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,co,Colombia",
    "country": "Colombia",
    "symbol": "COP",
    "currency": "COP",
    "exchangerates": "4400",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Colombia & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "tj": {
    "titleindex": "Mobile Price In Tajikistan | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Tajikistan, Smartphone Price tj, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,tj,Tajikistan",
    "country": "Tajikistan",
    "symbol": "TJS",
    "currency": "TJS",
    "exchangerates": "10.138",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Tajikistan & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "sk": {
    "titleindex": "Mobile Price In Slovakia | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Slovakia, Smartphone Price sk, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,sk,Slovakia",
    "country": "Slovakia",
    "symbol": "\u20ac",
    "currency": "Euro",
    "exchangerates": "0.99",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Slovakia & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "fi": {
    "titleindex": "Mobile Price In Finland | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Finland, Smartphone Price fi, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,fi,Finland",
    "country": "Finland",
    "symbol": "\u20ac",
    "currency": "Euro",
    "exchangerates": "0.99",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Finland & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "cm": {
    "titleindex": "Mobile Price In Cameroon | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Cameroon, Smartphone Price cm, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,cm,Cameroon",
    "country": "Cameroon",
    "symbol": "CFA",
    "currency": "CFA",
    "exchangerates": "670",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Cameroon & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "jp": {
    "titleindex": "Latest Mobile Price In Japan | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Japan, Mobile Price jp, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,jp,Japan,pictures,photos",
    "country": "Japan",
    "symbol": "\u00a5",
    "currency": "JPY",
    "exchangerates": "136",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Japan & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "de": {
    "titleindex": "Latest Mobile Price In Germany | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Germany, Mobile Price de, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,de,Germany,pictures,photos",
    "country": "Germany",
    "symbol": "\u20ac",
    "currency": "Euro",
    "exchangerates": "0.99",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Germany & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "sl": {
    "titleindex": "Mobile Price In Sierra Leone | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Sierra Leone, Smartphone Price sl, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,sl,Sierra Leone",
    "country": "Sierra Leone",
    "symbol": "SLL",
    "currency": "SLL",
    "exchangerates": "1430",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Sierra Leone & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "lb": {
    "titleindex": "Mobile Price In Lebanon | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Lebanon, Smartphone Price lb, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,lb,Lebanon",
    "country": "Lebanon",
    "symbol": "LBP",
    "currency": "LBP",
    "exchangerates": "1550",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Lebanon & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "gh": {
    "titleindex": "Latest Mobile Price In Ghana | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Ghana, Mobile Price gh, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,gh,Ghana,pictures,photos",
    "country": "Ghana",
    "symbol": "GHS",
    "currency": "GHS",
    "exchangerates": "8.75",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Ghana & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "mt": {
    "titleindex": "Mobile Price In Malta | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Malta, Smartphone Price mt, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,mt,Malta",
    "country": "Malta",
    "symbol": "\u20ac",
    "currency": "Euro",
    "exchangerates": "0.99",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Malta & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "iq": {
    "titleindex": "Mobile Price In Iraq | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Iraq, Smartphone Price iq, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,iq,Iraq",
    "country": "Iraq",
    "symbol": "IQD",
    "currency": "IQD",
    "exchangerates": "1485",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Iraq & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "na": {
    "titleindex": "Mobile Price In Namibia | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Namibia, Smartphone Price na, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,na,Namibia",
    "country": "Namibia",
    "symbol": "NAD",
    "currency": "NAD",
    "exchangerates": "17.463",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Namibia & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "bo": {
    "titleindex": "Mobile Price In Bolivia | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Bolivia, Smartphone Price bo, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,bo,Bolivia",
    "country": "Bolivia",
    "symbol": "BOB",
    "currency": "BOB",
    "exchangerates": "6.93",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Bolivia & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "rw": {
    "titleindex": "Mobile Price In Rwanda | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Rwanda, Smartphone Price rw, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,rw,Rwanda",
    "country": "Rwanda",
    "symbol": "RWF",
    "currency": "RWF",
    "exchangerates": "1060",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Rwanda & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "no": {
    "titleindex": "Mobile Price In Norway | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Norway, Smartphone Price no, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,no,Norway",
    "country": "Norway",
    "symbol": "NOK",
    "currency": "NOK",
    "exchangerates": "10.08",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Norway & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "dk": {
    "titleindex": "Mobile Price In Denmark | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Denmark, Smartphone Price dk, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,dk,Denmark",
    "country": "Denmark",
    "symbol": "DKK",
    "currency": "DKK",
    "exchangerates": "7.4",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Denmark & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "nl": {
    "titleindex": "Latest Mobile Price In Netherlands | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Netherlands, Mobile Price nl, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,nl,Netherlands,pictures,photos",
    "country": "Netherlands",
    "symbol": "\u20ac",
    "currency": "Euro",
    "exchangerates": "0.99",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Netherlands & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "cz": {
    "titleindex": "Mobile Price In Czech Republic | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Czech Republic, Smartphone Price cz, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,cz,Czech Republic",
    "country": "Czech Republic",
    "symbol": "CZK",
    "currency": "CZK",
    "exchangerates": "24",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Czech Republic & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "br": {
    "titleindex": "Latest Mobile Price In Brazil | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Brazil, Mobile Price br, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,br,Brazil,pictures,photos",
    "country": "Brazil",
    "symbol": "R$",
    "currency": "BRL",
    "exchangerates": "5.2",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Brazil & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "mk": {
    "titleindex": "Mobile Price In Macedonia | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Macedonia, Smartphone Price mk, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,mk,Macedonia",
    "country": "Macedonia",
    "symbol": "MKD",
    "currency": "MKD",
    "exchangerates": "64",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Macedonia & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "tz": {
    "titleindex": "Mobile Price In Tanzania | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Tanzania, Smartphone Price tz, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,tz,Tanzania",
    "country": "Tanzania",
    "symbol": "TZS",
    "currency": "TZS",
    "exchangerates": "2331",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Tanzania & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "sy": {
    "titleindex": "Mobile Price In Syrian | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Syrian, Smartphone Price sy, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,sy,Syrian",
    "country": "Syrian",
    "symbol": "SYP",
    "currency": "SYP",
    "exchangerates": "2512",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Syrian & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ke": {
    "titleindex": "Latest Mobile Price In Kenya | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Kenya, Mobile Price ke, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,ke,Kenya,pictures,photos",
    "country": "Kenya",
    "symbol": "KES",
    "currency": "KES",
    "exchangerates": "125",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Kenya & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "es": {
    "titleindex": "Latest Mobile Price In Spain | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Spain, Mobile Price es, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,es,Spain,pictures,photos",
    "country": "Spain",
    "symbol": "\u20ac",
    "currency": "Euro",
    "exchangerates": "0.99",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Spain & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ba": {
    "titleindex": "Mobile Price In Bosnia | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Bosnia, Smartphone Price ba, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,ba,Bosnia",
    "country": "Bosnia",
    "symbol": "BAM",
    "currency": "BAM",
    "exchangerates": "1.95",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Bosnia & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "tw": {
    "titleindex": "Latest Mobile Price In Taiwan | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Taiwan Mobile Price tw, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,tw,Taiwan,pictures,photos",
    "country": "Taiwan",
    "symbol": "NT$",
    "currency": "TWD",
    "exchangerates": "31.1",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Taiwan & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "th": {
    "titleindex": "Mobile Price In Thailand | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Thailand, Smartphone Price th, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,th,Thailand",
    "country": "Thailand",
    "symbol": "THB",
    "currency": "THB",
    "exchangerates": "36.615",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Thailand & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "pe": {
    "titleindex": "Mobile Price In Peru | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Peru, Smartphone Price pe, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,pe,Peru",
    "country": "Peru",
    "symbol": "PEN",
    "currency": "PEN",
    "exchangerates": "3.9",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Peru & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "tn": {
    "titleindex": "Prix \u200b\u200bdu t\u00e9l\u00e9phone portable en Tunisie | Sp\u00e9cifications compl\u00e8tes du t\u00e9l\u00e9phone",
    "descriptionindex": "Latest Mobile Phone Price in Tunisia, Smartphone Price tn, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,sp\u00e9cifications,informations,infos,tn,Tunisie",
    "country": "Tunisia",
    "symbol": "TND",
    "currency": "TND",
    "exchangerates": "3.25",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Tunisia & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "us": {
    "titleindex": "Mobile Phones Specifications, news and price info | MobGsm",
    "descriptionindex": "The ultimate resource in the United States is the price of GSM mobile phones. New android smartphone, tablet, features, full specifications, news information.",
    "keywordsindex": "mobgsm,mobile,phones,price,specifications,information",
    "country": "United States",
    "symbol": "$",
    "currency": "USD",
    "exchangerates": "1",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "Latest GSM Mobiles Phones News  | MobGsm",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Full Specifications",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "sd": {
    "titleindex": "Mobile Price In Sudan | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Sudan, Smartphone Price sd, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,sd,Sudan",
    "country": "Sudan",
    "symbol": "SDG",
    "currency": "SDG",
    "exchangerates": "580",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Sudan & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "gr": {
    "titleindex": "Mobile Price In Greece | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Greece, Smartphone Price gr, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,gr,Greece",
    "country": "Greece",
    "symbol": "\u20ac",
    "currency": "Euro",
    "exchangerates": "0.99",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Greece & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "pt": {
    "titleindex": "Mobile Price In Portugal | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Portugal, Smartphone Price pt, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,pt,Portugal",
    "country": "Portugal",
    "symbol": "\u20ac",
    "currency": "Euro",
    "exchangerates": "0.99",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Portugal & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "in": {
    "titleindex": "Latest Mobile Price In India | Full Mobile Phone Specifications",
    "descriptionindex": "Latest Mobile Phone Price in India, Mobile Price IN, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "Mobile Price in India, Phone Prices in India, Mobile Prices in India 2021, Mobile Price List in India, Phone Price List in India 2021",
    "country": "India",
    "symbol": "INR",
    "currency": "INR",
    "exchangerates": "84",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "Latest Mobiles Phones news 2021",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in India & Phones Specifications",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "zm": {
    "titleindex": "Mobile Price In Zambia | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Zambia, Smartphone Price zm, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,zm,Zambia",
    "country": "Zambia",
    "symbol": "ZMW",
    "currency": "ZMW",
    "exchangerates": "27",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Zambia & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ro": {
    "titleindex": "Mobile Price In Romania | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Romania, Smartphone Price ro, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,ro,Romania",
    "country": "Romania",
    "symbol": "RON",
    "currency": "RON",
    "exchangerates": "4.93",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Romania & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ec": {
    "titleindex": "Mobile Price In Ecuador | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Ecuador, Smartphone Price ec, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,ec,Ecuador",
    "country": "Ecuador",
    "symbol": "ECS",
    "currency": "ECS",
    "exchangerates": "26600",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Ecuador & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "za": {
    "titleindex": "Mobile Price In South Africa | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in South Africa, Smartphone Price za, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,za,South Africa",
    "country": "South Africa",
    "symbol": "ZAR",
    "currency": "ZAR",
    "exchangerates": "18.6",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in South Africa & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "id": {
    "titleindex": "Harga Ponsel Terbaru di Indonesia | Spesifikasi Lengkap Ponsel",
    "descriptionindex": "Harga Ponsel Terbaru di Indonesia, Harga Ponsel id, Penawaran dan Spek sebelum membeli Smartphone dari Toko online.",
    "keywordsindex": "ponsel,Nokia,Apple,iPhone,Motorola,Xiaomi,Samsung,Oppo,Oneplus,spesifikasi,informasi,info,id,Indonesia,gambar,foto",
    "country": "Indonesia",
    "symbol": "Rp",
    "currency": "IDR",
    "exchangerates": "14841.80",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Harga di Indonesia & penuh Spesifikasi",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "fr": {
    "titleindex": "Latest Mobile Price In France | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in France, Mobile Price fr, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,fr,France,pictures,photos",
    "country": "France",
    "symbol": "\u20ac",
    "currency": "Euro",
    "exchangerates": "0.99",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in France & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "pg": {
    "titleindex": "Mobile Price In Papua New Guinea | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Papua New Guinea, Smartphone Price pg, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,pg,Papua New Guinea",
    "country": "Papua New Guinea",
    "symbol": "PGK",
    "currency": "PGK",
    "exchangerates": "3.53",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Papua New Guinea & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "by": {
    "titleindex": "Mobile Price In Belarus | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Belarus, Smartphone Price by, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,by,Belarus",
    "country": "Belarus",
    "symbol": "BYR",
    "currency": "BYR",
    "exchangerates": "2.6",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Belarus & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "se": {
    "titleindex": "Mobile Price In Sweden | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Sweden, Smartphone Price se, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,se,Sweden",
    "country": "Sweden",
    "symbol": "SEK",
    "currency": "SEK",
    "exchangerates": "10.692",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Sweden & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ru": {
    "titleindex": "Latest Mobile Price In Russia | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Russia, Mobile Price ru, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,ru,Russia,pictures,photos",
    "country": "Russia",
    "symbol": "\u0440\u0443\u0431",
    "currency": "RUB",
    "exchangerates": "59.90",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Russian & Phones Specifications",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "kz": {
    "titleindex": "Mobile Price In Kazakhstan | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Kazakhstan, Smartphone Price kz, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,kz,Kazakhstan",
    "country": "Kazakhstan",
    "symbol": "KZT",
    "currency": "KZT",
    "exchangerates": "490",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Kazakhstan & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "jo": {
    "titleindex": "Mobile Price In Jordan | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Jordan, Smartphone Price jo, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,jo,Jordan",
    "country": "Jordan",
    "symbol": "JOD",
    "currency": "JOD",
    "exchangerates": "0.7303092783505155",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Jordan & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "vn": {
    "titleindex": "Latest Mobile Price In Viet Nam | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Viet Nam, Mobile Price vn, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,vn,Viet Nam,pictures,photos",
    "country": "Viet Nam",
    "symbol": "VND",
    "currency": "VND",
    "exchangerates": "23635",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Viet Nam & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ph": {
    "titleindex": "Latest Mobile Price In Philippines | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Philippines, Mobile Price ph, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,ph,Philippines,pictures,photos",
    "country": "Philippines",
    "symbol": "PHP",
    "currency": "PHP",
    "exchangerates": "57.06",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Philippines & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "mz": {
    "titleindex": "Mobile Price In Mozambique | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Mozambique, Smartphone Price mz, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,mz,Mozambique",
    "country": "Mozambique",
    "symbol": "MZN",
    "currency": "MZN",
    "exchangerates": "63.88",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Mozambique & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "hn": {
    "titleindex": "Mobile Price In Honduras | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Honduras, Smartphone Price hn, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,hn,Honduras",
    "country": "Honduras",
    "symbol": "HNL",
    "currency": "HNL",
    "exchangerates": "24.7",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Honduras & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "jm": {
    "titleindex": "Mobile Price In Jamaica | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Jamaica, Smartphone Price jm, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,jm,Jamaica",
    "country": "Jamaica",
    "symbol": "JM$",
    "currency": "JMD",
    "exchangerates": "155",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Jamaica & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "gl": {
    "titleindex": "Mobile Price In Greenland | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Greenland, Smartphone Price gl, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,gl,greenland",
    "country": "Greenland",
    "symbol": "DKK",
    "currency": "DKK",
    "exchangerates": "7.4",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Greenland & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "eg": {
    "titleindex": "Mobile Price In Egypt | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Egypt, Smartphone Price eg, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,eg,Egypt",
    "country": "Egypt",
    "symbol": "EGP",
    "currency": "EGP",
    "exchangerates": "47.12",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Egypt & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ma": {
    "titleindex": "Mobile Price In Morocco | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Morocco, Smartphone Price ma, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,ma,Morocco",
    "country": "Morocco",
    "symbol": "MAD",
    "currency": "MAD",
    "exchangerates": "10.77",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Morocco & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "sc": {
    "titleindex": "Mobile Price In Seychelles | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Seychelles, Smartphone Price sc, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,sc, seychelles",
    "country": "Seychelles",
    "symbol": "SCR",
    "currency": "SCR",
    "exchangerates": "15",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in  Seychelles & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "uy": {
    "titleindex": "Mobile Price In Uruguay | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Uruguay, Smartphone Price uy, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,uy,Uruguay",
    "country": "Uruguay",
    "symbol": "UYU",
    "currency": "UYU",
    "exchangerates": "42",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Uruguay & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ch": {
    "titleindex": "Mobile Price In Switzerland | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Switzerland, Smartphone Price ch, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,ch,Switzerland",
    "country": "Switzerland",
    "symbol": "CHF",
    "currency": "CHF",
    "exchangerates": "0.963",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Switzerland & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ng": {
    "titleindex": "Mobile Price in Nigeria | Latest Phone Specs & Reviews",
    "descriptionindex": "Latest Mobile Phone Price in Nigeria, Smartphone Price ng, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,ng,Nigeria",
    "country": "Nigeria",
    "symbol": "NGN",
    "currency": "NGN",
    "exchangerates": "670",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Nigeria & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "do": {
    "titleindex": "Mobile Price In Dominican | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Dominican, Smartphone Price do, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,do,Dominican",
    "country": "Dominican",
    "symbol": "DOP",
    "currency": "DOP",
    "exchangerates": "54.6",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Dominican & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "om": {
    "titleindex": "Latest Mobile Price In Oman | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Oman, Mobile Price om, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,om,Oman,pictures,photos",
    "country": "Oman",
    "symbol": "OMR",
    "currency": "OMR",
    "exchangerates": "0.4105",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Oman & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "nz": {
    "titleindex": "Mobile Price In New Zealand | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in New Zealand, Smartphone Price nz, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,nz,New Zealand",
    "country": "New Zealand",
    "symbol": "NZ$",
    "currency": "USD",
    "exchangerates": "1.66",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in New Zealand & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ye": {
    "titleindex": "Mobile Price In Yemen | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Yemen, Smartphone Price ye, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,ye,Yemen",
    "country": "Yemen",
    "symbol": "YER",
    "currency": "YER",
    "exchangerates": "250.21",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Yemen & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "kr": {
    "titleindex": "Latest Mobile Price In Korea (South) | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Korea (South), Mobile Price kr, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,kr,Korea (South),pictures,photos",
    "country": "Korea (South)",
    "symbol": "\u20a9",
    "currency": "KRW",
    "exchangerates": "1392",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Korea (South) & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "be": {
    "titleindex": "Mobile Price In Belgium | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Belgium, Smartphone Price be, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,be,Belgium",
    "country": "Belgium",
    "symbol": "\u20ac",
    "currency": "Euro",
    "exchangerates": "0.99",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Belgium & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "eu": {
    "titleindex": "Mobile Price In Europe | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Europe, Smartphone Price eu, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,eu,europe",
    "country": "Europe",
    "symbol": "\u20ac",
    "currency": "Euro",
    "exchangerates": "0.91",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Europe & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "hu": {
    "titleindex": "Mobile Price In Hungary | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Hungary, Smartphone Price hu, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,hu,Hungary",
    "country": "Hungary",
    "symbol": "HUF",
    "currency": "HUF",
    "exchangerates": "395",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Hungary & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "af": {
    "titleindex": "Latest Mobile Price In Afghanistan | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Afghanistan, Mobile Price af, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,af,Afghanistan,pictures,photos",
    "country": "Afghanistan",
    "symbol": "AFN",
    "currency": "AFN",
    "exchangerates": "95",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Afghanistan & Phones Specifications",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ht": {
    "titleindex": "Mobile Price In Haiti | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Haiti, Smartphone Price ht, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,ht,Haiti",
    "country": "Haiti",
    "symbol": "HTG",
    "currency": "HTG",
    "exchangerates": "126",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Haiti & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "zw": {
    "titleindex": "Mobile Price In Zimbabwe | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Zimbabwe, Smartphone Price zw, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,zw,Zimbabwe",
    "country": "Zimbabwe",
    "symbol": "ZWD",
    "currency": "ZWD",
    "exchangerates": "363",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Zimbabwe & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ua": {
    "titleindex": "Mobile Price In Ukraine | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Ukraine, Smartphone Price ua, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,ua,Ukraine",
    "country": "Ukraine",
    "symbol": "UAH",
    "currency": "UAH",
    "exchangerates": "37.2",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Ukraine & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "md": {
    "titleindex": "Mobile Price In Moldova | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Moldova, Smartphone Price md, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,md,Moldova",
    "country": "Moldova",
    "symbol": "MDL",
    "currency": "MDL",
    "exchangerates": "19.5",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Moldova & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "il": {
    "titleindex": "Mobile Price In Israel | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Israel, Smartphone Price il, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,il,Israel",
    "country": "Israel",
    "symbol": "ILS",
    "currency": "ILS",
    "exchangerates": "3.35",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Israel & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ae": {
    "titleindex": "Mobile Price In UAE Dubai | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in UAE Dubai, Smartphone Price ae, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,ae,UAE Dubai",
    "country": "UAE Dubai",
    "symbol": "AED",
    "currency": "AED",
    "exchangerates": "3.75",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in UAE Dubai & Mobile Specs",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "am": {
    "titleindex": "Mobile Price In Armenia | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Armenia, Smartphone Price am, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,am,Armenia",
    "country": "Armenia",
    "symbol": "AMD",
    "currency": "AMD",
    "exchangerates": "485",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Armenia & Mobile Specs",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "kw": {
    "titleindex": "Latest Mobile Price In Kuwait | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Kuwait, Mobile Price kw, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,kw,Kuwait,pictures,photos",
    "country": "Kuwait",
    "symbol": "KWD",
    "currency": "KWD",
    "exchangerates": "0.309",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Kuwait & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "mu": {
    "titleindex": "Mobile Price In Mauritius | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Mauritius, Smartphone Price mu, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,mu,Mauritius",
    "country": "Mauritius",
    "symbol": "MUR",
    "currency": "MUR",
    "exchangerates": "46",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Mauritius & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "et": {
    "titleindex": "Mobile Price In Ethiopia | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Ethiopia, Smartphone Price et, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,et,Ethiopia",
    "country": "Ethiopia",
    "symbol": "ETB",
    "currency": "ETB",
    "exchangerates": "57.39",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Ethiopia & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "it": {
    "titleindex": "Latest Mobile Price In Italy | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Italy, Mobile Price it, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,it,Italy,pictures,photos",
    "country": "Italy",
    "symbol": "\u20ac",
    "currency": "Euro",
    "exchangerates": "0.99",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Italy & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "pk": {
    "titleindex": "Mobile Price In Pakistan | Smartphone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Pakistan, Smartphone Price pk, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,pk,Pakistan,pictures,photos",
    "country": "Pakistan",
    "symbol": "Rs",
    "currency": "Rs",
    "exchangerates": "230",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Pakistan & Smartphone Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "sa": {
    "titleindex": "Latest Mobile Price In Saudi Arabia | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Saudi Arabia, Mobile Price sa, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,sa,Saudi Arabia,pictures,photos",
    "country": "Saudi Arabia",
    "symbol": "SAR",
    "currency": "SAR",
    "exchangerates": "3.82",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Saudi Arabia & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "az": {
    "titleindex": "Mobile Price In Azerbaijan | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Azerbaijan, Smartphone Price az, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,az,Azerbaijan",
    "country": "Azerbaijan",
    "symbol": "AZN",
    "currency": "AZN",
    "exchangerates": "1.75",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Azerbaijan & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "pl": {
    "titleindex": "Latest Mobile Price In Poland | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Poland, Mobile Price pl, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,pl,Poland,pictures,photos",
    "country": "Poland",
    "symbol": "z\u0142",
    "currency": "PLN",
    "exchangerates": "4.72",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Poland & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ar": {
    "titleindex": "Latest Mobile Price In Argentina | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Argentina, Mobile Price ar, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,ar,Argentina,pictures,photos",
    "country": "Argentina",
    "symbol": "$",
    "currency": "ARS",
    "exchangerates": "137",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Argentina & Full Phones Specifications",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "dz": {
    "titleindex": "Mobile Price In Algeria | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Algeria, Smartphone Price dz, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,dz,Algeria",
    "country": "Algeria",
    "symbol": "DZD",
    "currency": "DZD",
    "exchangerates": "148",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Algeria & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "my": {
    "titleindex": "Latest Mobile Price In Malaysia | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Malaysia, Mobile Price my, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,my,Malaysia,pictures,photos",
    "country": "Malaysia",
    "symbol": "MYR",
    "currency": "MYR",
    "exchangerates": "4.5",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Malaysia & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "bh": {
    "titleindex": "Latest Mobile Price In Bahrain | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Bahrain, Mobile Price bh, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,bh,Bahrain,pictures,photos",
    "country": "Bahrain",
    "symbol": "BHD",
    "currency": "BHD",
    "exchangerates": "0.3904",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Bahrain & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "au": {
    "titleindex": "Mobile Price In Australia | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Australia, Smartphone Price au, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,au,Australia",
    "country": "Australia",
    "symbol": "AUD",
    "currency": "AUD",
    "exchangerates": "1.48",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Australia & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "mx": {
    "titleindex": "Mobile Price In Mexico | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Mexico, Smartphone Price mx, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,mx,Mexico",
    "country": "Mexico",
    "symbol": "MXN",
    "currency": "MXN",
    "exchangerates": "20.5",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Mexico & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "cn": {
    "titleindex": "Latest Mobile Price In China | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in China, Mobile Price cn, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,cn,China,pictures,photos",
    "country": "China",
    "symbol": "\u00a5",
    "currency": "CNY",
    "exchangerates": "7.06",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in China & Full Phones Specifications",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "bd": {
    "titleindex": "Latest Mobile Price In Bangladesh | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Bangladesh, Mobile Price BD, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,bd,Bangladesh,pictures,photos",
    "country": "Bangladesh",
    "symbol": "Tk",
    "currency": "BDT",
    "exchangerates": "119",
    "brandconten": "<p><strong>Xiaomi</strong> is a well-established and worldwide well-known <strong>Chinese smartphone manufacturer</strong> of today. The reasons behind the success of Xiaomi are few. First of all, they have something to offer in about any price range, from low to very high. Then, Xiaomi phones have a reputation for stable software and hardware quality. Their phones usually offer a fine combination of specs with attractive pricing to meet consumer expectations. The modern and elegant design of their phones is also noticeable. Xiaomi phones are also known for their smooth and consistent performance offered for the low-mid and mid-range consumers. Battery life and camera quality are usually admirable as well. Moreover, they have a comprehensive insight into the buyer demand in various regions and budget groups. Enthusiasm, generosity, expertise and vision are some words that explain Xiaomi well.</p><h3>History</h3><p>Xiaomi is a relatively new brand in the phone industry. <strong>Their first smartphone Xiaomi Mi 1 was released back in August 2011</strong>. But within a very short period, at the end of 2014, they became the number one smartphone brand in the competitive market of China which was a country of 1.4 Billion people at that time. After China, Xiaomi has expanded its business to the USA and gained an excellent response from the consumers. But they have aimed high and decided to become one of the major brands in the global smartphone scene. Their success in China and in the USA helped them achieve this goal in less than three years. By the end of 2017, they were among the five top-selling smartphone brands in the world. In January 2019, Xiaomi opened the biggest Mi Store of Europe in Paris to establish their strong presence and continuous growth in Europe.</p><h3>Xiaomi in Bangladesh</h3><p><strong>On 10th August 2016, Xiaomi introduced their smartphones in Bangladesh</strong> in a conference in Grameenphone Corporate Office. Xiaomi primarily launched three smartphones in the Bangladeshi market together with Grameenphone and their authorized distributor in Bangladesh Solar Electro BD. It took only about half a year for them to gain a significant amount of consumer response. It all started with the launch of Xiaomi Redmi Note 4 in February 2017. This low-mid range phone was \u201cthe ultimate smartphone\u201d for its time for a vast number of smartphone enthusiasts in Bangladesh. The features were exceptionally versatile, the design was simply elegant, the performance was superior and the price was unbeatable. After that, they kept producing impressive phones to draw new buyers. At the beginning of 2018, they became the most searched smartphone brand online in Bangladesh. Brands like Samsung, Symphony, Huawei or Oppo were behind them. Then <strong>in 17th July 2018, Xiaomi officially entered Bangladeshi market with its own brand entity</strong>. Now, they are operating the business by themselves and not through their local distributor. Xiaomi is among the top brands to the young generation of Bangladesh in 2019. Mi A2 Lite, Redmi 6, Redmi 6A, Redmi S2 are some of their most successful recent releases. Xiaomi plans to establish a manufacturing factory in Bangladesh in the near future.</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Bangladesh & Phones Specs",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "np": {
    "titleindex": "Latest Mobile Price In Nepal | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Nepal, Mobile Price np, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,np,Nepal,pictures,photos",
    "country": "Nepal",
    "symbol": "NPR",
    "currency": "NPR",
    "exchangerates": "139",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Nepal & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "at": {
    "titleindex": "Mobile Price In Austria | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Austria, Smartphone Price at, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,at,Austria",
    "country": "Austria",
    "symbol": "\u20ac",
    "currency": "Euro",
    "exchangerates": "0.98",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Austria & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ug": {
    "titleindex": "Latest Mobile Price In Uganda | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Uganda, Mobile Price ug, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,ug,Uganda,pictures,photos",
    "country": "Uganda",
    "symbol": "UGX",
    "currency": "UGX",
    "exchangerates": "3816",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Uganda & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "cl": {
    "titleindex": "Mobile Price In Chile | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Chile, Smartphone Price cl, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,cl,Chile",
    "country": "Chile",
    "symbol": "CLP",
    "currency": "CLP",
    "exchangerates": "950",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Chile & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ir": {
    "titleindex": "Latest Mobile Price In Iran | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Iran, Mobile Price ir, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,ir,Iran,pictures,photos",
    "country": "Iran",
    "symbol": "IRR",
    "currency": "IRR",
    "exchangerates": "42320",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Iran & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "qa": {
    "titleindex": "Mobile Price In Qatar | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Qatar, Smartphone Price qa, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,qa,Qatar",
    "country": "Qatar",
    "symbol": "QAR",
    "currency": "QAR",
    "exchangerates": "3.64",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Qatar & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "lt": {
    "titleindex": "Mobile Price In Lithuania | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Lithuania, Smartphone Price lt, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,lt,Lithuania",
    "country": "Lithuania",
    "symbol": "\u20ac",
    "currency": "Euro",
    "exchangerates": "0.99",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Lithuania & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "lv": {
    "titleindex": "Mobile Price In Latvia | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Latvia, Smartphone Price lv, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,lv,Latvia",
    "country": "Latvia",
    "symbol": "\u20ac",
    "currency": "Euro",
    "exchangerates": "0.99",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Latvia & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "lk": {
    "titleindex": "Latest Mobile Price In Sri Lanka | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Sri Lanka, Mobile Price lk, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,lk,Sri Lanka,pictures,photos",
    "country": "Sri Lanka",
    "symbol": "LKR",
    "currency": "LKR",
    "exchangerates": "370",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Sri Lanka & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ms": {
    "titleindex": "Latest Mobile Price In Montserrat | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Montserrat, Mobile Price ms, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,ms,Montserrat,pictures,photos",
    "country": "Montserrat",
    "symbol": "$",
    "currency": "XCD",
    "exchangerates": "2.9",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Montserrat & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "sb": {
    "titleindex": "Mobile Price In Solomon Islands | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Solomon Islands, Smartphone Price sb, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,sb,Solomon Islands",
    "country": "Solomon Islands",
    "symbol": "SBD",
    "currency": "SBD",
    "exchangerates": "8.3",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Solomon Islands & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ao": {
    "titleindex": "Mobile Price In Angola | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Angola, Smartphone Price ao, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,ao,Angola",
    "country": "Angola",
    "symbol": "AON",
    "currency": "AON",
    "exchangerates": "435",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Angola & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ve": {
    "titleindex": "Mobile Price In Venezuela | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Venezuela, Smartphone Price ve, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,ve,Venezuela",
    "country": "Venezuela",
    "symbol": "VES",
    "currency": "VES",
    "exchangerates": "7.99",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Venezuela & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "mg": {
    "titleindex": "Mobile Price In Madagascar | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Madagascar, Smartphone Price mg, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,mg,Madagascar",
    "country": "Madagascar",
    "symbol": "MGA",
    "currency": "MGA",
    "exchangerates": "4300",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Madagascar & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "pr": {
    "titleindex": "Mobile Price In Puerto Rico | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Puerto Rico, Smartphone Price pr, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,pr,Puerto Rico",
    "country": "Puerto Rico",
    "symbol": "\u20ac",
    "currency": "Euro",
    "exchangerates": "0.99",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Puerto Rico & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "tr": {
    "titleindex": "Latest Mobile Price In Turkey | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Turkey, Mobile Price tr, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,tr,Turkey,pictures,photos",
    "country": "Turkey",
    "symbol": "\u20a4",
    "currency": "TRY",
    "exchangerates": "32.20",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Turkey & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "uk": {
    "titleindex": "Mobile Price In United Kingdom | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in United Kingdom, Smartphone Price uk, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,uk,United Kingdom",
    "country": "United Kingdom",
    "symbol": "GBP",
    "currency": "GBP",
    "exchangerates": "0.835",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in United Kingdom & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "mw": {
    "titleindex": "Mobile Price In Malawi | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Malawi, Smartphone Price mw, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,mw,Malawi",
    "country": "Malawi",
    "symbol": "MWK",
    "currency": "MWK",
    "exchangerates": "1050",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Malawi & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "uz": {
    "titleindex": "Mobile Price In Uzbekistan | Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Uzbekistan, Smartphone Price uz, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,specifications,information,info,uz,Uzbekistan",
    "country": "Uzbekistan",
    "symbol": "UZS",
    "currency": "UZS",
    "exchangerates": "10900",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Price in Uzbekistan & Mobile Specs | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  },
  "ca": {
    "titleindex": "Latest Mobile Price In Canada | Mobile Phone Full Specifications",
    "descriptionindex": "Latest Mobile Phone Price in Canada, Mobile Price ca, Offers and Specs before buying a Smartphone from online Store.",
    "keywordsindex": "mobile,phone,Nokia,Sony,Apple,iPhone,Motorola,Alcatel,Xiaomi,Samsung,Oppo,Oneplus,cellphone,specifications,information,info,ca,Canada,pictures,photos",
    "country": "Canada",
    "symbol": "CAN$",
    "currency": "USD",
    "exchangerates": "1.33",
    "brandconten": "<p>&nbsp;</p>",
    "titlenews": "",
    "descriptionnews": "",
    "keywordsnews": "",
    "titledevices": "Mobile Price in Canada & Full Phones Specifications | MobGsm",
    "descriptiondevices": "",
    "keywordsdevices": ""
  }
}